meta_product_name: "Soplex"
meta_title: "Soplex - Train Whenever, Wherever"
meta_description: "Find sports trainings in your neighbourhood. Invite your friends and discover great sports!"
meta_image: "soplex_fb_picture.jpg"                       # should exist in `app/assets/images/`
twitter_account: "@soplex"   # required for Twitter Cards
